Python 3.10.2 (tags/v3.10.2:a58ebcc, Jan 17 2022, 14:12:15) [MSC v.1929 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license()" for more information.
x=10
print(x)
10
a=5
print(a)
5
p=10
q=5
print(p>q)
True
print(p==q)
False
x=12
y=13
print(x and y)
13
print(x or y)
12
print(not x)
False
a=5
b=3
print(a&b)
1
print(a/b)
1.6666666666666667
number = [1,2,3,4,6]
print(2 in number)   #o/p=true
True
print(5 in number)   #o/p=false
False
x = 10
y = 10
print(x is y)
True
print(x is not y)
False
